development:
  stripe_publishable_key: pk_test_LYuucWicrc6BPNFHgXbIAUeS00EmsgUNiM
  stripe_secret_key: sk_test_ikkb3LwvOvrlPYlwzLBw4Ocs00eRtYbDRZ

production:
  stripe_publishable_key: ENV['pk_test_LYuucWicrc6BPNFHgXbIAUeS00EmsgUNiM']
  stripe_secret_key: ENV['sk_test_ikkb3LwvOvrlPYlwzLBw4Ocs00eRtYbDRZ']

